### ISSUE TITLE
Proxy usage

### ISSUE THREAD

**Issue by tpickett** [jprichardson/node-google#13]
I see your using request for getting the source, any way you could pass in an object to request instead of just the URL?
That we you could set a proxy property on the google variable and use that property (if set) as the value for the proxy key in the request object. 

I could send a pull request in a couple of days. just a little busy at the moment. that ok?

**Comment by chovy** [comment]
+1

**Comment by tpickett** [comment]
It is there now, should be in the README:


    var google = require('google');
    google.proxy = 'http://user:password@192.168.5.4:80';
    google('node.js best practices', function(err, next, links){
      …
    });

**Comment by jprichardson** [comment]
Yep, @tpickett is right. It's in the README. I guess we could modify the README to make that more clear, but closing this issue since it's supported behavior thanks to the work that @tpickett did.
