### ISSUE TITLE
Not returning on console.

### ISSUE THREAD

**Issue by dlinx** [jprichardson/node-google#18]
I need only two searches, when I wrote node program for it and execute, its not returning back on console, I need to press ctrl+c. This will create memory leak problem when you use it with expressjs

**Comment by teomaragakis** [comment]
I can verify this. I just did a: `google -q "cosmetics"` (everything left to default) and it never stops running. I don't think snippets will help, it's just a bunch of regular results and then nothing.

**Comment by jprichardson** [comment]
Console has been extract as of version 1.0. Closing.
