### ISSUE TITLE
`Next` detection for languages different from `en`

### ISSUE THREAD

**Issue by coire1** [jprichardson/node-google#24]
The `Next` string used to detect if the next page is present is hardcoded.
If you set a language different from `en` you can't go after the first page because the string to be used for detection changes with language.

Expose a config variable `google.nextText` for the `Next` string and warn user if language is not `en` and `google.nextText` string is the default one would be useful. Another option is to map the next string for every language.

What do you think?

**Comment by jprichardson** [comment]
Sounds good.

On Sunday, April 5, 2015, Lucio Baglione <notifications@github.com> wrote:

> The Next string used to detect if the next page is present is hardcoded.
> If you set a language different from en you can't go after the first page
> because the string to be used for detection changes with language.
>
> Expose a config variable google.nextText for the Next string and warn
> user if language is not en and google.nextText string is the default one
> would be useful. Another option is to map the next string for every
> language.
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jprichardson/node-google/issues/24>.
>


-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson
