### ISSUE TITLE
Question: what rate limiting are you all seeing?

### ISSUE THREAD

**Issue by bradvogel** [jprichardson/node-google#27]
I'm experimenting with how many searches I can do a minute without getting the captcha. So far I'm up to 4 searches a minute.

How many are you all able to do? Any tricks?

**Comment by jprichardson** [comment]
Please do not post requests on how to get around Google blocking automated search requests. It's outside the scope of this repository. Thanks.

Also, see: https://github.com/jprichardson/node-google/issues/20#issuecomment-74289023
