### ISSUE TITLE
QUESTION: About how many searches google might consider ABUSE

### ISSUE THREAD

**Issue by yayolius** [jprichardson/node-google#31]
i need to get about 500.000 domains with dot something so i will be calling this a lot, i don't know i would be able to prevent the "abuse".

Thanks
Claudio

**Comment by jprichardson** [comment]
https://github.com/jprichardson/node-google#nodejs---google which states:

> Please do not post an issue, email me, tweet me, or in anyway contact me about getting around Google blocking your automated search requests. These sorts of requests are outside the scope of this module. Google has every right to block consumers of their service for any reason.

**Comment by jprichardson** [comment]
To answer your question, I have no idea what Google would consider abuse.

**Comment by yayolius** [comment]
i was not triying to get around blocking, just triying to know what was abuse, in order to know how to limit my own prorgram.

i tries to get like 500 articles and was marked as blocked, so you know
