### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by SkullyKiddo** [jprichardson/node-google#37]
When using the API as:
google(slackComment.toLowerCase().replace('.google ',''), function (err, next, links){
			for (var i = 0; i < links.length; ++i) {
				console.log(links[i].title + ' - ' + links[i].link) // link.href is an alias for link.link
				console.log(links[i].description + "\n")
			}
			var botPayload = {
				text : "google unavailable"
			};
			respond(res, userName, botPayload);
		})

links variable is always empty.

**Comment by jprichardson** [comment]
Please try `1.4.0`.

**Comment by franciskim** [comment]
Nice update, fixed my issue. @jprichardson

**Comment by jprichardson** [comment]
:+1:
