### ISSUE TITLE
HOW to NOT get banned (see a captcha)?

### ISSUE THREAD

**Issue by thebarty** [jprichardson/node-google#57]
Hi guys,

this module works really nice, 

BUT BUT BUT: it STOPPS working pretty quick as **google shows me a CAPTCHA**.

HOW do you guys prevent that from happening? 

I am planning to do around 1000 queries per day.

Has anyone tried out running thru proxies? There are services offering private proxies... ???

**Comment by jprichardson** [comment]
You must not have read the third paragraph in the readme:

> Please do not post an issue, email me, tweet me, or in anyway contact me about getting around Google blocking your automated search requests. These sorts of requests are outside the scope of this module. Google has every right to block consumers of their service for any reason. See: #27, #20.

**Comment by thebarty** [comment]
Why close this topic? It is totally related to the userbase of this npm module? PLUS right now it seems like I wasted my time on this and should have better spend it writing my own webdriverio solution

**Comment by jprichardson** [comment]
I closed the topic because of the what I highlighted above.
